name: historia_clinica
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # --- Dependencias para consumir tu API REST ---
  dio: ^5.0.0          # Cliente HTTP avanzado
  http: ^1.6.0         # Opcional (si quieres usar ambos)

  # --- Arquitectura, estado y DI ---
  provider: ^6.0.0
  get_it: ^8.0.0       # Inyección de dependencias

  # --- Para modelos inmutables y generación automática ---
  freezed_annotation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # --- Generación automática de código (para Freezed) ---
  build_runner:
  freezed:

flutter:
  uses-material-design: true
